### ISSUE TITLE
Leading comments break compiling

### ISSUE THREAD

**Issue by deniaz** [ryanbahniuk/scss-to-json#13]
The following SCSS file

```scss
/**
 * Test
 */

$foo: 'bar';
```

leads to the following error:

```
<path>/node_modules/node-sass/lib/index.js:440
  throw assign(new Error(), JSON.parse(result.error));
  ^

Error: Invalid CSS after ".test { content:": expected expression (e.g. 1px, bold), was "/** };"
    at Object.module.exports.renderSync (<path>/node_modules/node-sass/lib/index.js:440:16)
    at Object.fromString (<path>/node_modules/scss-to-json/src/compile.js:17:18)
    at Value._parse (<path>/node_modules/scss-to-json/src/value.js:17:28)
    at Value (<path>/node_modules/scss-to-json/src/value.js:11:8)
    at Declaration._parse (<path>/node_modules/scss-to-json/src/declaration.js:26:18)
    at Declaration (<path>/node_modules/scss-to-json/src/declaration.js:14:8)
    at <path>/node_modules/scss-to-json/src/processor.js:90:12
    at Array.map (native)
    at declarationsFromString (<path>/node_modules/scss-to-json/src/processor.js:89:16)
    at new Processor (<path>/node_modules/scss-to-json/src/processor.js:104:18)
```

Yet `node-sass` will compile it correctly. I might investigate further and create a PR if I find something.

**Comment by Saturate** [comment]
I can confirm this issue, it's breaking on all of my files.

**Comment by leifdejong** [comment]
Issue confirmed from https://github.com/intoli/antd-scss-theme-plugin/blob/635cba72b5d491c7921d31716e13eae974ca54fd/src/utils.js#L48
